name: Ensembler
channels:
  - conda-forge
  - defaults
dependencies:
  #Required environment for developing Ensembler
  - ipywidgets
  - jupyter
  - matplotlib
  - mpmath
  - nbsphinx
  - numpy
  - pandas
  - pip
  - scipy
  - sphinx
  - m2r
  - sympy
  - tqdm
  - typing
  - wheel
  - rdkit
  - codecov
  - pytest
  - pytest-cov
  - pre-commit