name: Ensembler
channels:
  - conda-forge
  - defaults
dependencies:
  #Minimally required environment for using Ensembler
  - ipywidgets
  - jupyter
  - matplotlib
  - mpmath
  - numpy
  - pandas
  - pip
  - scipy
  - sympy
  - tqdm
  - typing
  - wheel
  - rdkit
