# Configure LGTM for this package

extraction:
  python:  # Configure Python
    python_setup:  # Configure the setup
      version: 3  # Specify Version 3

path_classifiers:
  exclude:
    - ensembler/test
    - examples
    - setup.py
    - versioneer.py

  library:
    - versioneer.py  # Set Versioneer.py to an external "library" (3rd party code)
    - devtools/*
  generated:
    - ensembler/_version.py
