name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  test:
    name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      # More info on options: https://github.com/goanpeca/setup-miniconda
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: devtools/conda-envs/test_env.yaml

          channels: conda-forge,defaults

          activate-environment: test
          auto-update-conda: truea
          auto-activate-base: false
          show-channel-urls: true

      - name: Install package

        # conda setup requires this special shell
        shell: bash -l {0}
        run: |
          python -m pip install . --no-deps
          conda list

      - name: Run tests

        # conda setup requires this special shell
        shell: bash -l {0}

        run: |
          pytest  -v --cov=ensembler --cov-report=xml --color=yes ensembler/tests/

      - name: Run example notebooks

        # conda setup requires this special shell
        shell: bash -l {0}

        continue-on-error: true

        run: |
          # add --ignore=XXX here to ignore file XXX
          PYTEST_ARGS+=" --nbval-lax "
          pytest $PYTEST_ARGS examples/

      - name: CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
